FROM node:14

WORKDIR /contracts

COPY package.json yarn.lock ./
RUN yarn

COPY truffle-config.js truffle-config.js
COPY ./precompiled ./precompiled
COPY ./contracts ./contracts
RUN yarn compile

COPY flatten.sh flatten.sh
RUN yarn flatten

COPY deploy.sh deploy.sh
COPY ./deploy ./deploy
COPY ./test ./test
COPY ./e2e-tests ./e2e-tests

ENV PATH="/contracts/:${PATH}"
